# Generated by Django 6.0.1 on 2026-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('room', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'in_call',
            },
        ),
    ]
